DROP TABLE IF EXISTS lessons;
DROP TABLE IF EXISTS one_offs;
DROP TABLE IF EXISTS subjects;
DROP TABLE IF EXISTS events;
DROP INDEX IF EXISTS idx_one_offs_user_id;
DROP INDEX IF EXISTS idx_one_offs_schedule_date;
DROP INDEX IF EXISTS idx_subjects_user_id;
DROP INDEX IF EXISTS idx_subjects_teaching_days;
DROP INDEX IF EXISTS idx_lessons_subject_id;
DROP INDEX IF EXISTS idx_events_user_id;
DROP INDEX IF EXISTS idx_events_user_id_event_date;
DROP INDEX IF EXISTS idx_events_event_type_event_id;
DROP FUNCTION IF EXISTS generate_lesson_schedule_dates(INTEGER, TEXT[], DATE);
DROP FUNCTION IF EXISTS generate_subject_events(UUID, UUID);
DROP FUNCTION IF EXISTS generate_one_off_events(UUID, UUID);
DROP FUNCTION IF EXISTS insert_subject(JSONB);
DROP FUNCTION IF EXISTS insert_one_off(JSONB);
DROP FUNCTION IF EXISTS get_user_events_with_titles(JSONB);
DROP FUNCTION IF EXISTS get_next_order_index(UUID, DATE, INTEGER);
DROP FUNCTION IF EXISTS valid_move(UUID, DATE);
DROP FUNCTION IF EXISTS move_event(JSONB);